---
title: "Indexer Example"
---

## Basic Indexing

Some text with this *term* {{< indexer_add_term term >}} indexed.

or

Other text with this *term* {{< indexer add term >}} indexed.

## Index a Term and Display Text

Index {{< indexer add *this* idxdisplay='' >}} word and display it at the same time.

or

Index {{< indexer add *this* idxdisplay='*this*' >}} word and display it at the same time.

or

Index {{< indexer_add_term *this* idxdisplay='' >}} word and display it at the same time.

or

Index {{< indexer_add_term *this* idxdisplay='*this*' >}} word and display it at the same time.

---

Display {{< indexer add 'other *compound*' idxdisplay='*this* and that' >}} words, but index it under "other *compound*".

or

Display {{< indexer_add_term 'other *compound*' idxdisplay='*this* and that' >}} words, but index it under "other *compound*".

## Custom Index SortKey

Display {{< indexer add '$\delta$-other' idxdisplay='' idxsortkey='delta-other' >}} words, but use "delta-other" as the *sortkey*.

or

Display {{< indexer_add_term '$\delta$-other' idxdisplay='' idxsortkey='*delta-other*' >}} words, but use "*delta-other*" as the *sortkey*.

## See Other Term

Display {{< indexer add this idxdisplay='' idxsee='that' >}} word, and add *see* *that* {{< indexer add that >}} word.

or

Display {{< indexer_add_term this idxdisplay='' idxsee='that' >}} word, and add *see* *that* {{< indexer add that >}} word.

## Term Nesting

Display {{< indexer add this idxdisplay='' idxnesting='random ! words' >}} word, and *nest* it under *words $\rightarrow$ random $\rightarrow$ this*.

or

Display {{< indexer_add_term this idxdisplay='' idxnesting='random ! words' >}} word, and *nest* it under *words $\rightarrow$ random $\rightarrow$ this*.

## Term Suffix

Display {{< indexer add Surname idxdisplay='Firstname Surname' idxnesting='names' idxsuffix='Firstnme' >}}, and index it as *Surname* nested under *names*, with a suffix *Firstname*.

or

Display {{< indexer_add_term Surname idxdisplay='Firstname Surname' idxnesting='names' idxsuffix='Firstnme' >}}, and index it as *Surname* nested under *names*, with a suffix *Firstname*.

## Styling Index

Display {{< indexer add OtherSurname idxdisplay='OtherFirstname OtherSurname' idxnesting='names' idxsuffix='OtherFirstnme' idxstyle=defidxsty >}}, and index it as *OtherSurname* nested under *names*, with a suffix *OtherFirstname*;
style it with the default style (`defidxsty`).

or

Display {{< indexer_add_term OtherSurname idxdisplay='OtherFirstname OtherSurname' idxnesting='names' idxsuffix='OtherFirstnme' idxstyle=defidxsty >}}, and index it as *OtherSurname* nested under *names*, with a suffix *OtherFirstname*;
style it with the default style (`defidxsty`).

---

## Basic Defining

Define {{< definer *this* >}} term.

Define {{< definer *this* defstyle='defdefsty' >}} term with the default style: `defdefsty`.

Define {{< definer *this* defstyle='defdefsty' defindex='' >}} term with the default style (`defdefsty`) and index it as such.

Now pass some options to the indexer.
Define {{< definer *this* defstyle='defdefsty' defindex='custom' idxnesting='def ! inition' >}} term with the default style (`defdefsty`) and index it as such.

## Printing the Index

{{< indexer_print >}}

or

{{< indexer print >}}
